# Generated by Django 3.0 on 2022-03-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_categort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categort',
            new_name='category',
        ),
    ]
