# Generated by Django 3.0 on 2022-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220302_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='decription',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
