# Generated by Django 3.0 on 2022-03-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220306_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phon',
            new_name='phone',
        ),
    ]
