# Generated by Django 3.0 on 2022-03-12 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20220312_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quqantity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 12, 12, 27, 21, 984067)),
        ),
    ]
